[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "foundry-devops=lib/foundry-devops",
    "account-abstraction/contracts=lib/account-abstraction/contracts"
]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable", "mixed-case-function"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
