[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/local/=lib/chainlink-local/",
    "@chainlink/ccip/=lib/ccip/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@aave/v3/core/contracts/=lib/aave-v3-core/contracts/",
    "foundry-devops/=lib/foundry-devops/",
    "account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "aave-address-book/src/=lib/aave-address-book/src/",
    "aave-v3-origin/=lib/aave-address-book/lib/aave-v3-origin/src/"
]

auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = true

rpc_endpoints = { ethSepolia = "http://localhost:8546", avaFuji = "http://localhost:8547"}

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read-write", path = "script/config" }
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable", "mixed-case-function"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
